#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find /mnt/disk/learning-dir/ /mnt/disk/coding-projects/ /home/ -mindepth 0 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -ds $selected_name -c $selected
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if [[ -n $TMUX ]]; then
  tmux switch-client -t $selected_name
else
  tmux attach -t $selected_name
fi

exit 0
